name: Run pre-commit on all branches

on:
  push:
    branches:
      - "**" # Ejecutar en todas las ramas
  pull_request:
    branches:
      - "**" # Ejecutar en todos los PRs, independientemente de la rama

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create venv
        run: |
          uv venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install pre-commit poetry
          pre-commit install

      - name: Run pre-commit on all files
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: Ensure lock files are unchanged
        run: git diff --exit-code poetry.lock package-lock.json
